slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver_type: SPARSE_NORMAL_CHOLESKY
    ceres_linear_solver_threads: 1
    ceres_threads: 4
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    map_file_name: multi_room_map
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_travel_distance: 0.5
    minimum_rotation_radians: 0.5
    use_scan_matching: true
    use_scan_bagging: false
    aggressive_reset: false
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Matcher params
    use_response_expansion: true
    enable_scan_matcher_publisher: true
    published_map_resolution: 0.05
    scan_buffer_size: 10
    scan_buffer_max_scan_beams: 3000
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_queue_length: 9
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    correlation_response_threshold: 0.7
    loop_search_space_dimension: 8.0
    map_correlation_scan_point_reduction: 5

    # Processor params
    use_scan_matching: true
    max_iterations: 10
    epsilon_xy: 0.00001
    epsilon_theta: 0.000001
    search_window_coarse: 0.3
    search_window_fine: 0.1
    angle_variance_penalty_factor: 1.0
    min_angle_penalty_to_transfer_fine_search: 0.99
    outliers_max_per_processed_scan: 300
    outliers_double_sided: false
    outliers_publish_vertices: true
    outliers_separate_evaluation: false
    cleaning_polygon_index: 0
    scan_point_cloud_angle_offset: 90.0
    scan_point_cloud_range_min: 0.0
    scan_point_cloud_range_max: 30.0
    scan_point_cloud_range_tolerance: 0.0

